[package]
name = "feo3boy-memdev-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
derive-syn-parse = "0.1"
syn = { version = "2", features = ["full"] }
proc-macro2 = "1"
proc-macro-crate = "1"
quote = "1"
